--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BestCodrEver/CustomVoidLevel
build-by-default: true
branches:
- main
projects:
  CustomVoidLevel:
    path: ""
    icon: "icon.png"
    excludeFiles:
     - "README.md"
     - "LICENSE"
...
